-------------------------------------------------------------------------------
-- Script       : 413_evaluate_models_svm_unigram.sql
-- Purpose      : Predict the TREAD category of test data using the SVM model
--                
-- Author(s)    : Tim Santos
-- History      : 20151203 – Tim Santos – Initial Version
--
-------------------------------------------------------------------------------   

---------------------------------------------------------------------------------
-- Test Data labeled using Unigram SVM Model
-- Table is generated by SPARSESVMPREDICTOR SQL-MR
-- Make sure to drop the table before running the SQL-MR function
-- @column		: 'compdesc_category' - ground truth
-- @column		: 'predict_value' - SVM prediction
---------------------------------------------------------------------------------
DROP TABLE IF EXISTS car_complaints.nhtsa_1gram_svm_output;

-------------------------------------------------------------------------------
-- Train SVM classifier model 
-- @input		: car_complaints.nhtsa_test_1gram_tfidf
-- @input		: car_complaints.nhtsa_1gram_svm_model
-- @output		: car_complaints.nhtsa_1gram_svm_output
-- @param		: VALUECOLUMN('tf_idf') - use tfidf for prediction
-- @param		: ACCUMULATELABEL('compdesc_category') - include the 
--				  ground truth in the output, for evaluation purposes
-------------------------------------------------------------------------------   
SELECT *
FROM   SPARSESVMPREDICTOR(
                           ON (SELECT 1)
                           PARTITION BY 1
                           INPUTTABLE('car_complaints.nhtsa_test_1gram_tfidf')
                           MODELTABLE('car_complaints.nhtsa_1gram_svm_model')
                           OUTPUTTABLE('car_complaints.nhtsa_1gram_svm_output')
                           SAMPLEIDCOLUMN('cmplid')
                           ATTRIBUTECOLUMN('token')
                           VALUECOLUMN('tf_idf')
                           ACCUMULATELABEL('compdesc_category')
                         );  


---------------------------------------------------------------------------------
-- Confusion matrix evaluation of Unigram SVM Model
-- Table is to be generated by CONFUSIONMATRIXPLOT SQL-MR function
-- Make sure to drop the table before running the SQL-MR function
-- @column[2-10]: TREAD categories
-- @column      : miss
-- @column 		: recall
-- @row 		: false_alarm
-- @row 		: precision
-- @row 		: f-measure 1.0
-- @row 		: accuracy
---------------------------------------------------------------------------------
DROP TABLE IF EXISTS car_complaints.nhtsa_1gram_svm_metrics;                         
                         
-------------------------------------------------------------------------------
-- Script       : CONFUSIONMATRIXPLOT
-- Purpose      : Create confusion matrix to evaluate SVM prediction
-- @input		: car_complaints.nhtsa_test
-- @input		: car_complaints.nhtsa_1gram_svm_output
-- @output		: car_complaints.svm_nhtsa_1gram_plot
-- @param		: EXPECTCOLUMN('compdesc_category') - ground truth
-- @param		: PREDICTCOLUMN('predict_value') - SVM prediction
-------------------------------------------------------------------------------   
SELECT *
FROM   CONFUSIONMATRIXPLOT(
                            ON (
                                 SELECT *
                                 FROM CONFUSIONMATRIX(
                                                       ON (
                                                            SELECT     tw.cmplid
                                                                      ,tw.cdescr
                                                                      ,tw.compdesc_category
                                                                      ,predict_value
                                                            FROM       car_complaints.nhtsa_test tw
                                                            INNER JOIN car_complaints.nhtsa_1gram_svm_output classify 
                                                            ON         classify.cmplid = tw.cmplid
                                                          )
                                                       PARTITION BY compdesc_category
                                                       EXPECTCOLUMN('compdesc_category')
                                                       PREDICTCOLUMN('predict_value')
                                                    )
                               )
                            PARTITION BY 1
                            OUTPUTTABLE('car_complaints.nhtsa_1gram_svm_metrics')
                            BETA(1.0)
                          );
                           
-------------------------------------------------------------------------------
-- Display the evaluation criteria for this model
-- @input		: car_complaints.nhtsa_1gram_svm_metrics
-- @output		: accuracy
-- @output		: precision
-- @output		: recall
-- @output 		: f-measure
-------------------------------------------------------------------------------                           
SELECT * FROM car_complaints.nhtsa_1gram_svm_metrics;       


