-------------------------------------------------------------------------------
-- Script       : 415_evaluate_models_maxent_unigram.sql
-- Purpose      : Predict the TREAD category of test data using the MaxEnt model
--                
-- Author(s)    : Tim Santos
-- History      : 20151203 – Tim Santos – Initial Version
-- TODO			: RECODE
-------------------------------------------------------------------------------   

-------------------------------------------------------------------------------
-- Evaluate MaxEnt classifier model 
-- @input		: car_complaints.nhtsa_test
-- @input		: car_complaints.car_complaints/nhtsa_1gram_maxent_model.bin
-- @output		: car_complaints.nhtsa_1gram_maxent_output
-- @param		: TEXTCOLUMN('cdescr')
-- @param		: ACCUMULATELABEL ('cmplid','cdescr','compdesc_category') 
--                include the actual text, id and 
--				  ground truth in the output, for evaluation purposes
-------------------------------------------------------------------------------   
INSERT INTO car_complaints.nhtsa_1gram_maxent_output 
SELECT *
FROM TextClassifier(
                     ON car_complaints.nhtsa_test
                     TEXTCOLUMN('cdescr')
                     MODEL('car_complaints.nhtsa_me_model')
                     ACCUMULATE('cmplid','cdescr','compdesc_category')
                   );

                   
---------------------------------------------------------------------------------
-- Confusion matrix evaluation of Unigram MaxEnt with Feature Selection
-- Table is generated by CONFUSIONMATRIXPLOT SQL-MR function
-- Make sure to drop the table before running the SQL-MR function
-- @column[2-10]: TREAD categories
-- @column      : miss
-- @column 		: recall
-- @row 		: false_alarm
-- @row 		: precision
-- @row 		: f-measure 1.0
-- @row 		: accuracy
---------------------------------------------------------------------------------
DROP TABLE IF EXISTS car_complaints.nhtsa_1gram_maxent_metrics;

-------------------------------------------------------------------------------
-- Create confusion matrix to evaluate MaxEnt prediction
-- @input		: car_complaints.nhtsa_test
-- @input		: car_complaints.nhtsa_1gram_maxent_output
-- @output		: car_complaints.nhtsa_1gram_maxent_metrics
-- @param		: EXPECTCOLUMN ('compdesc_category') - ground truth
-- @param		: PREDICTCOLUMN ('out_category') - MaxEnt prediction
-------------------------------------------------------------------------------   
SELECT *
FROM   CONFUSIONMATRIXPLOT(
                            ON (
                                 SELECT *
                                 FROM CONFUSIONMATRIX(
                                                       ON (
                                                            SELECT     tw.cmplid
                                                                      ,tw.cdescr
                                                                      ,tw.compdesc_category
                                                                      ,out_category as predict_value
                                                            FROM       car_complaints.nhtsa_test  tw
                                                            INNER JOIN car_complaints.nhtsa_1gram_maxent_output 
                                                                       classify 
                                                            ON         classify.cmplid = tw.cmplid
                                                          )
                                                       PARTITION BY compdesc_category
                                                       EXPECTCOLUMN('compdesc_category')
                                                       PREDICTCOLUMN('predict_value')
                                                     )
                               )
                            PARTITION BY 1
                            OUTPUTTABLE('car_complaints.nhtsa_1gram_maxent_metrics')
                            BETA(1.0)
                          );
                           
-------------------------------------------------------------------------------
-- Display the evaluation criteria for this model
-- @input		: car_complaints.nhtsa_1gram_maxent_metrics
-- @output		: accuracy
-- @output		: precision
-- @output		: recall
-- @output 		: f-measure
-------------------------------------------------------------------------------                           
SELECT * FROM car_complaints.nhtsa_1gram_maxent_metrics;       


